# Generated by Django 3.1.8 on 2021-05-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.IntegerField(default=30)),
                ('scopeAdjustment', models.CharField(max_length=50)),
                ('ammoWeight', models.IntegerField(default=150)),
                ('barrelLength', models.IntegerField(default=26)),
                ('currentZero', models.IntegerField(default=100)),
                ('windSpeed', models.IntegerField(default=0)),
                ('boreToSight', models.IntegerField(default=2)),
                ('shotAngle', models.IntegerField(default=0)),
                ('shooter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.shooter')),
            ],
        ),
    ]
