# Generated by Django 3.1.8 on 2021-06-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210601_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.IntegerField(default=30)),
                ('scopeAdjustment', models.IntegerField(default=4)),
                ('distance', models.IntegerField(default=30)),
                ('currentZero', models.IntegerField(default=100)),
                ('shooter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.shooter')),
            ],
        ),
    ]
